- hosts: all
  tasks:
          - name: creating a docker repository
            yum_repository:
                 description: "repo for docker"
                 name: "docker-ce"
                 baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
                 gpgcheck: "no"
             
          - name: installing docker
            package:
                  name: "docker-ce-18.09.1-3.el7.x86_64"
                  state: present
          
          - name: "starting docker service"
            service:
                   name: docker
                   state: started
          - name: installing python
            package:
                    name: "python3"
                    state: present
          - pip: 
                name: docker-py
                state: present

          - name: pulling docker image
            docker_image:
                   name: httpd
                   source: pull
          
          - file:
                  path: /sourav123
                  state: directory         
          - name: Copying file into home
            copy:
                 src: index2.html
                 dest: /home

          - name: Create a data container
            community.general.docker_container:
                      name: mydata
                      image: httpd 
                      exposed_ports: "80"
                      ports:
                          -  "82:80"
                      state: started
                      detach: yes
                      volumes: /sourav123:/usr/local/apache2/htdocs/
