- hosts: tag_Name_Haproxy
  vars_files:
        var.yml
  tasks:
  - name: "Installing {{ software_name }}"
    package: 
      name: "{{ lb_software_name }}"
      state: present

  - name: "Configuration File"
    template:
      src: "haproxy.cfg.j2"
      dest: "/etc/haproxy/haproxy.cfg"
  - name: "Starting Services"
    service:
      name: "{{ lb_software_name }}"
      state: started

- hosts: tag_Name_WebServer 
  tasks:
  - name: "Installing Apache Software"
    package:
      name: "httpd"
      state: present
  - name : "php install "
    package:
      name : "php"
      state : present

  - name: "Copying Webpages.."
    copy:
       src: "my.php"
       dest: "/var/www/html"
    notify: "Restart Services"

  - name: "Starting Service"
    service:
      name: "httpd"
      state: started
  handlers:
  - name: "Restart Services"
    service:
      name:  "httpd"
      state: restarted
     
