- hosts: tag_Name_k8s_master
  vars_files:
          var.yml
  tasks:
  - name: "namespace created"
    shell: "kubectl create ns {{ ns_name }}"
  - name: "role create"
    shell: "kubectl create role {{ role_name }}  --verb=* --resource=* --namespace={{ ns_name }}"
  - name: "rolebinding create"
    shell: "kubectl create rolebinding {{rolebinding_name }}  --role={{ role_name }} -n {{ ns_name }} --user={{user_name }}"
  
