- hosts: web
  vars_files: 
     - myvar.yml
  tasks:
  - name: installing httpd software
    package: 
        name: "httpd"
        state: present
  - name: create document root 
    file: 
        state: directory
        path: "{{ doc_root }}"
  - name: "Configuring the conf file for document root and port number"
    template:
        dest: "/etc/httpd/conf.d/sourav.conf"
        src: "sourav.conf"
    notify:
    - restart_apache_httpd 
  - name: "copying the content of website in document root folder"
    copy:
        dest: "{{ doc_root }}/index.html"
        src: "index.html"
  - name: "ensure apache is running"
    service:
          name: "httpd"
          state: started

  handlers:
    - name: "restart_apache_httpd"
      service:
        name: "httpd"
        state: restarted
